// Task 3c.20: the technical-sheets SQL generated by scripts/catalog/technical-sheets.mjs
// (here from the SYNTHETIC fixture; the real data is private) adds
// metadata.technical_sheet to existing rows without touching any other column,
// creates new items, reactivates inactive ones, is idempotent, and its rollback
// restores the exact prior rows (every column except the trigger-maintained updated_at).
import fs from 'node:fs';
import pg from 'pg';
import { afterAll, beforeAll, describe, expect, test } from 'vitest';
import { buildMigrationSql, buildRollbackSql } from '../../scripts/catalog/technical-sheets.mjs';

const enabled = process.env.TEST_PG_INTEGRATION === '1';
const describeIntegration = enabled ? describe : describe.skip;
const connection = {
  host: process.env.TEST_PGHOST || '127.0.0.1',
  port: Number(process.env.TEST_PGPORT || 55433),
  database: process.env.TEST_PGDATABASE || 'testdb',
  user: process.env.TEST_PGUSER || 'test',
  password: process.env.TEST_PGPASSWORD || 'test',
};
const data = JSON.parse(fs.readFileSync('tests/fixtures/catalog/technical-sheets.synthetic.json', 'utf8'));
const applySql = buildMigrationSql(data);
const rollbackSql = buildRollbackSql(data);
const SKUS = ['demo-existente', 'demo-inactivo', 'demo-nuevo', 'demo-servicio', 'demo-control'];
const item = (sku) => data.items.find((candidate) => candidate.sku === sku);

describeIntegration('catalog technical sheets SQL (synthetic data)', () => {
  const client = new pg.Client(connection);
  let before;

  const snapshot = async () => {
    const { rows } = await client.query(
      `SELECT to_jsonb(ci) - 'updated_at' AS row FROM catalog_items ci WHERE sku = ANY($1::text[]) ORDER BY sku`,
      [SKUS],
    );
    return rows.map((row) => row.row);
  };
  const rowBySku = async (sku) => (await client.query(
    `SELECT ci.*, cc.code AS category_code FROM catalog_items ci
     LEFT JOIN catalog_categories cc ON cc.id = ci.category_id WHERE ci.sku = $1`,
    [sku],
  )).rows[0];

  beforeAll(async () => {
    await client.connect();
    await client.query('BEGIN');
    await client.query('DELETE FROM catalog_items WHERE sku = ANY($1::text[])', [SKUS]);
    await client.query(`INSERT INTO catalog_categories (code, name) VALUES ('demo-categoria', 'Categoría Demo') ON CONFLICT (code) DO NOTHING`);
    await client.query(
      `INSERT INTO catalog_items (sku, name, item_type, short_description, is_active, metadata) VALUES
         ('demo-existente', 'Producto Demo A', 'product', 'descripción demo A', TRUE,
          '{"url": "https://example.test/demo-a", "synonyms": ["demo a"]}'::jsonb),
         ('demo-inactivo', 'Producto Demo B', 'product', NULL, FALSE, '{"url": "https://example.test/demo-b"}'::jsonb),
         ('demo-control', 'Producto Demo Control', 'product', NULL, TRUE, '{"url": "https://example.test/control"}'::jsonb)`,
    );
    before = await snapshot();
  });

  afterAll(async () => {
    if (enabled) {
      await client.query('ROLLBACK');
      await client.end();
    }
  });

  test('adds the sheet to the existing row and keeps its catalog columns and other metadata', async () => {
    await client.query(applySql);
    const row = await rowBySku('demo-existente');
    expect(row).toMatchObject({ name: 'Producto Demo A', short_description: 'descripción demo A', is_active: true });
    expect(row.metadata).toEqual({
      url: 'https://example.test/demo-a', synonyms: ['demo a'], technical_sheet: item('demo-existente').technical_sheet,
    });
    expect((await rowBySku('demo-control')).metadata).toEqual({ url: 'https://example.test/control' });
  });

  test('creates the new items in their category and reactivates the inactive one with its synonyms', async () => {
    for (const sku of ['demo-nuevo', 'demo-servicio']) {
      const row = await rowBySku(sku);
      const expected = item(sku);
      expect(row).toMatchObject({
        name: expected.name, item_type: expected.item_type, is_active: true,
        short_description: expected.short_description, category_code: 'demo-categoria',
      });
      expect(row.metadata).toEqual({
        catalog_migration_027: 'created',
        ...(expected.synonyms ? { synonyms: expected.synonyms } : {}),
        technical_sheet: expected.technical_sheet,
      });
    }
    const reactivated = await rowBySku('demo-inactivo');
    expect(reactivated.is_active).toBe(true);
    expect(reactivated.metadata).toEqual({
      url: 'https://example.test/demo-b', synonyms: item('demo-inactivo').synonyms,
      catalog_migration_027: 'reactivated', technical_sheet: item('demo-inactivo').technical_sheet,
    });
  });

  test('is idempotent: a second run affects no row', async () => {
    const afterFirst = await snapshot();
    const results = [].concat(await client.query(applySql));
    expect(results.map((result) => result.rowCount ?? 0).filter((count) => count > 0)).toEqual([]);
    expect(await snapshot()).toEqual(afterFirst);
  });

  test('the rollback restores the exact prior rows', async () => {
    await client.query(rollbackSql);
    expect(await snapshot()).toEqual(before);
  });

  test('a row that was already active is never deactivated by the rollback', async () => {
    await client.query("UPDATE catalog_items SET is_active = TRUE WHERE sku = 'demo-inactivo'");
    const activeBefore = await snapshot();
    await client.query(applySql);
    expect((await rowBySku('demo-inactivo')).metadata).not.toHaveProperty('catalog_migration_027');
    await client.query(rollbackSql);
    expect(await snapshot()).toEqual(activeBefore);
  });
});
